name: Run playwright on stage pcna

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "15 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: yarn
    - run: npx tsc
    - run: free -h
    - run: ls -a
    - run: node hello.js > logs/stagepcna.txt
    - run: git config user.name "Kushal Hada";
      if: always()
    - run: git config user.email "kus@tilde.team";
      if: always()
    - run: git add .;
      if: always()
    - run: git commit -m "add a hello world perf log" -m "perf matters";
      if: always()
    - run: git pull --rebase --strategy-option=theirs;
      if: always()
    - run: git push origin master;
      if: always()
